# Site settings
title: 동식이 블로그
SEOTitle: 동식이 블로그
header-img: img/home-bg.jpg
email: ehdtlr9376@gmail.com
description: "무슨 멘트?"
keyword: "동식, python, ssafy, django, aws, vue.js, web"
url: "https://dongsik93.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     huxpro
# zhihu_username:     huxpro
github_username:    dongsik93
instagram_username: dongsikkkkk2
# twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx
email: ehdtlr9376@naver.com


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate, jekyll-sitemap]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: dongsik93

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
google_analytics: UA-144665538-1
ga_track_id: 'UA-144665538-1'            # Format: UA-xxxxxx-xx
ga_domain: dongsik93.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "남들과 다르게 천천히 걷는 것만으로도 남들과 전혀 다른 삶이 된다"
sidebar-avatar: /img/avatar-dongsik.JPG     # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "강은주",
        href: "https://eunju-kang.github.io/"
    },
    {
        title: "김준영",
        href: "https://github.com/kjywow94/"
    },
    {
        title: "김혜빈",
        href: "https://kimhyebin.github.io/"
    },
    {
        title: "양시영",
        href: "https://dev-lagom.tistory.com/"
    },
    {
        title: "정태준",
        href: "https://TaeJuneJoung.github.io"
    },
    {
        title: "조병용",
        href: "https://jby3146.github.io/"
    },
    {
        title: "조신성",
        href: "https://tlstjd436.blog.me/"
    },
    {
        title: "조호근",
        href: "https://clearroot.github.io/"
    }
    
]
